---
title: "Multivariate Analysis - Mesquite"
subtitle: "adapted from IRC Data analysis for R2R summer institute 2021"
author: "Janet Gonzalez, Kelsey Hauf"
date: "last modified 2/27/24"
output: html_document
---

# Multivariate Analysis - Constrained Analysis

## Load Data

```{r}
library(tidyverse)
library(vegan)
library(ggplot2)
library(ggordiplots)
```

```{r}
Mesquite <-read.csv("Mesquite_AllData.csv")

```

```{r}
MesquiteDiff <- Mesquite %>%
    filter(
        (Site == 1)| 
        (Site == 5)
      )

MesquiteDiff <- MesquiteDiff |>
  mutate(Site = case_when(Site == "1" ~ "BSB", 
                          Site == "5" ~ "CDL"))
```

### NMDS

```{r}
numericonly <- MesquiteDiff |> select(Resprouting, CrownSizeShape, CrownFoliarDensity, DeadBranches)

mydata.mds <- metaMDS(numericonly, distance="bray", k=2, autotransform=FALSE, noshare = FALSE)

```

#### NMDS Plot 1

```{r}
plot(mydata.mds,type="t",display=c("species"))
```

```{r}
plot(mydata.mds,type="t",display=c("sites"))
```

```{r}
plot1 <- ordiplot(mydata.mds, choices=c(1,2)) 
```

#### NMDS Plot 2

```{r}
MesquiteDiff.sspfit <- gg_envfit(mydata.mds, numericonly) 


Misquite_points <- bind_cols(MesquiteDiff,MesquiteDiff.sspfit$df_ord)
Misquite_arrows <- MesquiteDiff.sspfit$df_arrows


library(ordr)

ggplot() + 
  geom_point(data = Misquite_points,  
             aes(x = x, y = y, color = Site)) + 
  geom_vector(data = Misquite_arrows, aes(x = x, y = y)) + 
  geom_text(data = Misquite_arrows, 
            aes(x = x, y = y, label = var), 
            vjust = 1)+ 
  labs(y = "NMDS2", x = "NMDS1")

 MesquiteDiff.sspfit$df_arrows
```

### CAP

```{r}
MesquiteDiff.cap <- capscale(numericonly ~ Site, MesquiteDiff, dist="bray") 
MesquiteDiff.cap
```

```{r}
scores(MesquiteDiff.cap)
```

#### PERMANOVA

```{r}
anova(MesquiteDiff.cap) 
```

#### CAP Plot 1

```{r}
plot(MesquiteDiff.cap, display=c("sp", "sites","cn"),type="text")
```

```{r}
plot(MesquiteDiff.cap, display=c("sp", "cn"),type="text")
```

#### CAP Plot 2

```{r}
gg_ordiplot(
    MesquiteDiff.cap,
    groups = MesquiteDiff$Site,
    scaling = 1,
    choices = c(1, 2),
    show.groups = "all",
    label = TRUE,
    hull = TRUE,
    ellipse = FALSE,
    spiders = FALSE,
    pt.size = 1,
    plot = TRUE
) 
```
